export default function() {
  return {
    municipality_list: [
      "AMAI MANABILANG (BUMBARAN)",
      "BACOLOD-KALAWI (BACOLOD GRANDE)",
      "BALABAGAN",
      "BALINDONG (WATU)",
      "BAYANG",
      "BINIDAYAN",
      "BUADIPOSO-BUNTONG",
      "BUTIG",
      "CALANOGAS",
      "DITSAAN-RAMAIN",
      "GANASSI",
      "KAPAI",
      "KAPATAGAN",
      "LUMBA-BAYABAO (MAGUING)",
      "LUMBACA-UNAYAN",
      "LUMBATAN",
      "LUMBAYANAGUE",
      "MADALUM",
      "MADAMBA",
      "MAGUING",
      "MALABANG",
      "MARANTAO",
      "MARAWI CITY",
      "MAROGONG",
      "MASIU",
      "MULONDO",
      "PAGAYAWAN (TATARIKAN)",
      "PIAGAPO",
      "PICONG (SULTAN GUMANDER)",
      "POONA BAYABAO (GATA)",
      "PUALAS",
      "SAGUIARAN",
      "SULTAN DUMALONDONG",
      "TAGOLOAN",
      "TAMPARAN",
      "TARAKA",
      "TUBARAN",
      "TUGAYA",
      "WAO",
    ],

    "AMAI MANABILANG (BUMBARAN)": [
      "BAGUMBAYAN",
      "BANDARA-INGUD",
      "COMARA",
      "FRANKFORT",
      "LAMBANOGAN",
      "LICO",
      "MANSILANO",
      "NATANGCOPAN",
      "PAGALAMATAN",
      "PAGONAYAN",
      "PIAGMA",
      "POBLACION (APARTFORT)",
      "PUNUD",
      "RANAO-BANING",
      "SAGUA-AN",
      "SALAM",
      "SUMUGOT",
    ],
    "BACOLOD-KALAWI (BACOLOD GRANDE)": [
      "AMPAO",
      "BAGOAINGUD",
      "BALUT",
      "BARUA",
      "BUADIAWANI",
      "BUBONG",
      "DARAMOYOD",
      "DILABAYAN",
      "DIPATUAN",
      "GANDAMATO",
      "GURAIN",
      "ILIAN",
      "LAMA",
      "LIAWAO",
      "LUMBACA-INGUD",
      "MADANDING",
      "ORONG",
      "PINDOLONAN",
      "POBLACION I",
      "POBLACION II",
      "RAYA",
      "ROROWAN",
      "SUGOD",
      "TAMBO",
      "TUKA I",
      "TUKA II",
    ],
    BALABAGAN: [
      "BAGOAINGUD",
      "BANAGO",
      "BARORAO",
      "BATUAN",
      "BUDAS",
      "BUENAVISTA",
      "BUISAN (BENGABENG)",
      "CALILANGAN",
      "IGABAY",
      "ILIAN",
      "LALABUAN",
      "LORENZO",
      "LOWER ITIL",
      "LUMBAC",
      "MACAO",
      "MAGULALUNG OCCIDENTAL",
      "MAGULALUNG ORIENTAL",
      "MATAMPAY",
      "MATANOG",
      "MOLIMOC",
      "NARRA",
      "PINDOLONAN",
      "PLASAN",
      "POBLACION (BALABAGAN)",
      "PURAKAN",
      "TATAYA",
      "UPPER ITIL",
    ],
    "BALINDONG (WATU)": [
      "ABAGA",
      "BANTOGA WATO",
      "BARIT",
      "BOLINSONG",
      "BORAKIS",
      "BUALAN",
      "BUBONG",
      "BUBONG CADAPAAN",
      "CADAPAAN",
      "CADAYONAN",
      "DADAYAG",
      "DADO",
      "DIBARUSAN",
      "DILAUSAN",
      "DIMARAO",
      "INGUD",
      "KALUNTAY",
      "LALABUAN",
      "LATI",
      "LILOD",
      "LIMBO",
      "LUMBAC LALAN",
      "LUMBAC WATO",
      "LUMBAYAO",
      "MAGARANG",
      "MALAIG",
      "NUSA LUMBA RANAO",
      "PADILA",
      "PAGAYAWAN",
      "PAIGOAY",
      "PANTARAGOO",
      "POBLACION (BALINDONG)",
      "RAYA",
      "SALIPONGAN",
      "TALUB",
      "TANTUA RAYA",
      "TOMAROMPONG",
      "TUKA BUBONG",
    ],
    BAYANG: [
      "BAGOAINGUD",
      "BAIRAN (POB.)",
      "BANDINGUN",
      "BIABI",
      "BIALAAN",
      "BUBONG LILOD",
      "BUBONG RAYA",
      "CADAYONAN",
      "CADINGILAN OCCIDENTAL",
      "CADINGILAN ORIENTAL",
      "CONDARAAN POB. (CONDARAAN DIMADAP)",
      "CORMATAN",
      "GANDAMATO",
      "ILIAN",
      "LALAPUNG CENTRAL",
      "LALAPUNG PROPER (POB.)",
      "LALAPUNG UPPER",
      "LINAO",
      "LINUK (POB.)",
      "LIONG",
      "LUMBAC",
      "LUMBAC CADAYONAN",
      "MALIWANAG",
      "MAPANTAO",
      "MIMBALAWAG",
      "PALAO",
      "PAMA-AN",
      "PAMACOTAN",
      "PANTAR",
      "PARAO",
      "PATONG",
      "POBLACION (BAYANG)",
      "POROTAN",
      "RANTIAN",
      "RAYA CADAYONAN",
      "RINABOR (POB.)",
      "SAMPORNA (POB.)",
      "SAPA",
      "SILID",
      "SUGOD",
      "SULTAN PANDAPATAN",
      "SUMBAG (POB.)",
      "TAGORANAO",
      "TANGCAL",
      "TANGCAL PROPER (POB.)",
      "TOMAROMPONG",
      "TOMONGCAL LIGI",
      "TOROGAN",
      "TUCA (POB.)",
    ],
    BINIDAYAN: [
      "BADAK",
      "BAGUIANGUN",
      "BALUT MAITO",
      "BASAK",
      "BUBONG",
      "BUBONGA-RANAO",
      "DANSALAN DACSULA",
      "INGUD",
      "KIALILIDAN",
      "LUMBAC",
      "MACAGUILING",
      "MADAYA",
      "MAGONAYA",
      "MAINDIG",
      "MASOLUN",
      "OLAMA",
      "PAGALAMATAN (POB.)",
      "PANTAR",
      "PICALILANGAN",
      "PICOTAAN",
      "PINDOLONAN",
      "POBLACION",
      "SOLDARORO",
      "TAMBAC",
      "TIMBANGAN",
      "TUCA",
    ],
    "BUADIPOSO-BUNTONG": [
      "BACOLOD",
      "BANGON",
      "BANGON PROPER",
      "BOTO RAGONDINGAN",
      "BUADIPOSO LILOD",
      "BUADIPOSO PROPER",
      "BUADIPOSO RAYA",
      "BUBONG",
      "BUNTONG PROPER",
      "CADAYONAN",
      "DANSALAN",
      "DATU TAMBARA",
      "DIRISAN",
      "GATA",
      "KALAKALA",
      "KATOGONAN",
      "LUMBAC",
      "LUMBATAN MANACAB",
      "LUMBATAN PATAINGUD",
      "LUNDUBAN (RAGONDINGAN)",
      "MANACAB (POB.)",
      "MINANGA (BUNTONG)",
      "PALING",
      "PINDOLONAN",
      "PUALAS",
      "RAGONDINGAN EAST",
      "RAGONDINGAN PROPER",
      "RAGONDINGAN WEST",
      "RAYA BUNTONG (BUNTONG EAST)",
      "SAPOT",
      "TANGCAL",
      "TARIK",
      "TUKA",
    ],
    BUBONG: [
      "BACOLOD",
      "BAGOAINGUD",
      "BANSAYAN",
      "BASINGAN",
      "BATANGAN",
      "BUALAN",
      "BUBONGA DIDAGUN",
      "CARIGONGAN",
      "DALAON",
      "DIBAROSAN",
      "DILABAYAN",
      "DIMAPATOY",
      "DIMAYON",
      "DIMAYON PROPER",
      "DIOLANGAN",
      "GUIGUIKUN",
      "MADANDING",
      "MALUNGUN",
      "MASOROT",
      "MATAMPAY DIMARAO",
      "MIABALAWAG",
      "MONTIAAN",
      "PAGAYAWAN",
      "PALAO",
      "PANALAWAN",
      "PANTAR",
      "PENDOGOAN",
      "PINDOLONAN",
      "POBLACION (BUBONG)",
      "POLAYAGAN",
      "PUNUD",
      "RAMAIN BUBONG",
      "ROGERO",
      "SALIPONGAN",
      "SUNGGOD",
      "TABORO",
    ],
    BUTIG: [
      "BAYABAO POBLACION",
      "BUTIG PROPER",
      "CABASARAN",
      "COLOYAN TAMBO",
      "DILIMBAYAN",
      "DOLANGAN",
      "MALUNGUN",
      "PINDOLONAN",
      "POKTAN",
      "RAGAYAN",
      "RAYA",
      "SAMER",
      "SANDAB MADAYA",
      "SUNDIG",
      "TIMBAB",
      "TIOWI",
    ],
    CALANOGAS: [
      "BUBONGA RANAO",
      "CALALAOAN (POB.)",
      "GAS",
      "INOMA",
      "INUDARAN",
      "LUGUNA",
      "MIMBALAWAG",
      "NGINGIR",
      "PAGALONGAN",
      "PANGGAWALUPA",
      "PANTAON",
      "PIKSAN",
      "PINDOLONAN",
      "PUNUD",
      "TAGORANAO",
      "TALIBOBOKA",
      "TAMBAC",
    ],
    "DITSAAN-RAMAIN": [
      "BACLAYAN LILOD",
      "BACLAYAN RAYA",
      "BAGOAINGUD",
      "BARIMBINGAN",
      "BAYABAO",
      "BUADI ALAO",
      "BUADI BABAI",
      "BUADI OLOC",
      "BUAYAAN LILOD",
      "BUAYAAN MADANDING",
      "BUAYAAN RAYA",
      "BUBONG DANGIPRAMPIAI",
      "DADO",
      "DANGIMPRAMPIAI",
      "DARIMBANG",
      "DILAUSAN",
      "DITSAAN",
      "GADONGAN",
      "LINAMON",
      "LUMBATAN RAMAIN",
      "MAINDIG DITSAAN",
      "MANDARA",
      "MARANAO TIMBER (DALAMA)",
      "PAGALONGAN BUADIADINGAN",
      "PAGALONGAN GINAOPAN",
      "PAGALONGAN MASIOON",
      "PAGALONGAN PROPER",
      "POLO",
      "RAMAIN POBLACION",
      "RAMAIN PROPER",
      "RANTIAN",
      "SULTAN PANGADAPUN",
      "SUNDIGA BAYABAO",
      "TALUB",
      "UPPER PUGAAN",
    ],
    GANASSI: [
      "BAGOAINGUD",
      "BALINTAD",
      "BALINTAD A",
      "BARIT",
      "BARORAO",
      "BATO BATORAY",
      "BAYA",
      "CAMPONG A RAYA",
      "CAMPONG SABELA",
      "DAPAAN",
      "GADONGAN",
      "GUI",
      "LINUK",
      "LUMBAC",
      "LUMBACAINGUD",
      "MACABAO",
      "MACAGUILING",
      "MASOLUN",
      "PAGALONGAN",
      "PAMALIAN",
      "PANGADAPUN",
      "PANGGAWALUPA",
      "PANTAON",
      "PANTAON A",
      "PARA-ABA",
      "PINDOLONAN",
      "POBLACION",
      "SEKUN MATAMPAY",
      "SOGOD MADAYA",
      "TABUAN",
      "TAGANONOK",
      "TALIOGON",
    ],
    KAPAI: [
      "BABAYOG",
      "CORMATAN",
      "DILABAYAN",
      "DILIMBAYAN",
      "DIMAGALING (DIMAGALIN PROPER)",
      "DIMUNDA",
      "DORONAN",
      "GADONGAN",
      "KASAYANAN",
      "KASAYANAN WEST",
      "KIBOLOS",
      "KINING",
      "LIDASAN",
      "MACADAR",
      "MALNA PROPER",
      "PAGALONGAN",
      "PANTAON",
      "PARAO",
      "PINDOLONAN",
      "POBLACION (KAPAI PROPER)",
    ],
    KAPATAGAN: [
      "BAKIKIS",
      "BARAO",
      "BONGABONG",
      "DAGUAN",
      "INUDARAN",
      "KABANIAKAWAN",
      "KAPATAGAN",
      "LUSAIN",
      "MATIMOS",
      "MINIMAO",
      "PINANTAO",
      "SALAMAN",
      "SIGAYAN",
      "TABUAN",
      "UPPER IGABAY",
    ],
    "LUMBA-BAYABAO (MAGUING)": [
      "BACOLOD I",
      "BACOLOD II",
      "BANTAYAO",
      "BARIT",
      "BAUGAN",
      "BUAD LUMBAC",
      "CABASARAN",
      "CALILANGAN",
      "CARANDANGAN-MIPAGA",
      "CORMATAN LANGBAN",
      "DIALONGANA",
      "DILINDONGAN-CADAYONAN",
      "GADONGAN",
      "GALAWAN",
      "GAMBAI",
      "KASOLA",
      "LALANGITUN",
      "LAMA",
      "LINDONGAN DIALONGANA",
      "LOBO BASARA",
      "LUMBAC BACAYAWAN",
      "MACAGUILING",
      "MAPANTAO",
      "MAPOLING",
      "MARIBO (POB.)",
      "MINARING DILADIGAN",
      "PAGAYAWAN",
      "POSUDARAGAT",
      "RUMAYAS",
      "SABALA BANTAYAO",
      "SALAMAN",
      "SALOLODUN BERWAR",
      "SARIGIDAN MADIAR",
      "SUNGGOD",
      "TALUAN",
      "TAMLANG",
      "TONGCOPAN",
      "TUROGAN",
    ],
    "LUMBACA-UNAYAN": [
      "BANGON (DILAUSAN)",
      "BETA",
      "CALALON",
      "CALIPAPA",
      "DILAUSAN",
      "DIMAPAOK",
      "LUMBAK-DILAUSAN",
      "ORIENTAL BETA",
      "TRINGUN",
    ],
    LUMBATAN: [
      "ALOG",
      "BASAYUNGUN",
      "BUAD",
      "BUBONG MACADAR",
      "BUDI",
      "DAGO-OK",
      "DALAMA",
      "DALIPUGA",
      "LALAPUNG",
      "LIGUE",
      "LUMBAC",
      "LUMBAC BACAYAWAN",
      "LUNAY",
      "MACADAR",
      "MADAYA",
      "MINANGA",
      "PANTAR",
      "PENARING",
      "PICOTAAN",
      "POBLACION (LUMBATAN)",
      "TAMBAC",
    ],
    LUMBAYANAGUE: [
      "BAGOAINGUD",
      "BALAIGAY",
      "BUALAN",
      "CABUNTUNGAN",
      "CADAYONAN",
      "CADINGILAN",
      "CADINGILAN A",
      "CASALAYAN",
      "DALA (DALAMA)",
      "DILIMBAYAN",
      "DIROMOYOD",
      "KABASARAN (POB.)",
      "LAMIN",
      "MAPANTAO-BALANGAS",
      "MINIROS",
      "NANAGUN",
      "PANTAON",
      "PINDOLONAN",
      "PITATANGLAN",
      "POCTAN",
      "SINGCARA",
      "WAGO",
    ],
    MADALUM: [
      "ABAGA",
      "BACAYAWAN",
      "BAGOAINGUD",
      "BASAK",
      "BATO",
      "BUBONG",
      "CABASARAN",
      "CADAYONAN",
      "DANDAMUN",
      "DELAUSAN",
      "DIAMPACA",
      "DIBAROSAN",
      "GADONGAN",
      "GURAIN",
      "KORMATAN",
      "LIANGAN",
      "LIANGAN I",
      "LILITUN",
      "LINAO",
      "LINUK",
      "LUMBAC",
      "MADAYA",
      "PADIAN TOROGAN I",
      "PAGAYAWAN",
      "PARIDI-KALIMODAN",
      "POBLACION",
      "PUNUD",
      "RACOTAN",
      "RAYA",
      "RIRAY",
      "SABANDING",
      "SALONGABANDING",
      "SOGOD KALOY",
      "SUGOD",
      "TAMPORONG",
      "TONGANTONGAN",
      "UDANGUN",
    ],
    MADAMBA: [
      "BALAGUNUN",
      "BALINTAD",
      "BAWANG",
      "BIABE",
      "BUBONG UYAAN",
      "CABASARAN",
      "DIBARUSAN",
      "ILIAN",
      "LAKITAN",
      "LIANGAN",
      "LINUK",
      "LUMBACA INGUD",
      "MADAMBA",
      "PAGAYONAN",
      "PALAO",
      "PANGADAPAN",
      "PANTAON",
      "PANTAR",
      "PUNUD",
      "TAMBO",
      "TUBARAN",
      "TUCA",
      "TULAY",
      "UYAAN PROPER (POB.)",
    ],
    MAGUING: [
      "AGAGAN",
      "BALAGUNUN",
      "BALAWAG",
      "BALINTAO",
      "BATO-BATO",
      "BOLAO",
      "BOROCOT",
      "BORROWA",
      "BOTUD",
      "BUADIANGKAY",
      "BUBONG",
      "BUBONG BAYABAO",
      "CAMALIG",
      "CAMBONG",
      "DILAUSAN (POB.)",
      "DILIMBAYAN",
      "ILALAG",
      "KIANODAN",
      "LILOD BOROCOT",
      "LILOD MAGUING",
      "LUMBAC",
      "LUMBAC-DIMARAO",
      "MADANDING",
      "MADAYA",
      "MAGUING PROPER",
      "MALUNGUN",
      "MALUNGUN BOROCOT",
      "MALUNGUN PAGALONGAN",
      "PAGALONGAN",
      "PANAYANGAN",
      "PILIMOKNAN",
      "PINDOLONAN",
      "RAGAYAN (RUNGAYAN)",
      "SABALA DILAUSAN",
    ],
    MALABANG: [
      "BACAYAWAN",
      "BADAK LUMAO",
      "BAGOAINGUD",
      "BANDAY",
      "BETAYAN",
      "BONIGA",
      "BPS VILLAGE",
      "BUNK HOUSE",
      "CABASARAN (SOUTH)",
      "CALIBAGAT",
      "CALUMBOG",
      "CAMPO MUSLIM",
      "CHINA TOWN (POB.)",
      "CORAHAB",
      "DIAMARO",
      "INANDAYAN",
      "JOSE ABAD SANTOS",
      "LAMIN",
      "MABLE",
      "MACURANDING",
      "MADAYA",
      "MANANAYO",
      "MANGGAHAN",
      "MASAO",
      "MATALIN",
      "MATAMPAY",
      "MATLING",
      "MONTAY",
      "PASIR",
      "PIALOT",
      "REBOCUN",
      "SARANG",
      "SUMBAGAROGONG",
      "TACUB",
      "TAMBARA",
      "TIONGCOP",
      "TUBOC",
    ],
    MARANTAO: [
      "BACAYAWAN",
      "BACONG",
      "BANGA-PANTAR",
      "BATAL-PUNUD",
      "BUBONG MADANDING (BUBONG)",
      "CAMALIG (POB.)",
      "CAMALIG BANDARA INGUD",
      "CAMALIG BUBONG",
      "CAWAYAN",
      "CAWAYAN BACOLOD",
      "CAWAYAN KALAW",
      "CAWAYAN LINUK",
      "DAANAINGUD",
      "ILIAN",
      "INUDARAN CAMPONG",
      "INUDARAN LOWAY",
      "INUDARAN LUMBAC",
      "KIALDAN",
      "LUBO",
      "LUMBAC KIALDAN",
      "MANTAPOLI",
      "MATAMPAY",
      "MAUL",
      "MAUL ILIAN",
      "MAUL LUMBACA INGUD",
      "NATARON",
      "PAGALONGAN BACAYAWAN",
      "PALAO",
      "PATAIMAS",
      "POBLACION",
      "POONA MARANTAO",
      "PUNUD PROPER",
      "TACUB",
      "TUCA KIALDAN",
    ],
    "MARAWI CITY": [
      "AMBOLONG",
      "AMITO MARANTAO",
      "BACOLOD CHICO PROPER",
      "BANGA",
      "BANGCO",
      "BANGGOLO POBLACION",
      "BANGON",
      "BASAK MALUTLUT",
      "BEYABA-DAMAG",
      "BITO BUADI ITOWA",
      "BITO BUADI PARBA",
      "BOGANGA",
      "BOTO AMBOLONG",
      "BUADI SACAYO (GREEN)",
      "BUBONG LUMBAC",
      "BUBONGA CADAYONAN",
      "BUBONGA LILOD MADAYA",
      "BUBONGA MARAWI",
      "BUBONGA PAGALAMATAN",
      "BUBONGA PUNOD",
      "CABASARAN",
      "CABINGAN",
      "CADAYONAN",
      "CADAYONAN I",
      "CALOCAN EAST",
      "CALOCAN WEST",
      "DAGUDUBAN",
      "DANSALAN",
      "DATU NAGA",
      "DATU SA DANSALAN",
      "DAYAWAN",
      "DIMALUNA",
      "DULAY",
      "DULAY WEST",
      "EAST BASAK",
      "EMIE PUNUD",
      "FORT",
      "GADONGAN",
      "GADONGAN MAPANTAO",
      "GUIMBA (LILOD PROPER)",
      "KAPANTARAN",
      "KILALA",
      "KORMATAN MATAMPAY",
      "LILOD MADAYA (POB.)",
      "LILOD SADUC",
      "LOMIDONG",
      "LUMBAC MARINAUT",
      "LUMBACA MADAYA (POB.)",
      "LUMBACA TOROS",
      "MALIMONO",
      "MARAWI POBLACION",
      "MARINAUT (MARINAUT WEST)",
      "MARINAUT EAST",
      "MATAMPAY",
      "MIPAGA PROPER",
      "MONCADO COLONY",
      "MONCADO KADINGILAN",
      "MORIATAO LOKSADATO",
      "NAVARRO (DATU SABER)",
      "NORHAYA VILLAGE",
      "OLAWA AMBOLONG",
      "PAGALAMATAN GAMBAI",
      "PAGAYAWAN",
      "PANGGAO SADUC",
      "PANTAON (LANGCAF)",
      "PAPANDAYAN",
      "PAPANDAYAN CANIOGAN",
      "PARIDI",
      "PATANI",
      "PINDOLONAN",
      "POONA MARANTAO",
      "PUGAAN",
      "RAPASUN MSU",
      "RAYA MADAYA I",
      "RAYA MADAYA II",
      "RAYA SADUC",
      "ROROGAGUS EAST",
      "ROROGAGUS PROPER",
      "SABALA MANAO",
      "SABALA MANAO PROPER",
      "SADUC PROPER",
      "SAGONSONGAN",
      "SANGCAY DANSALAN",
      "SOMIORANG",
      "SOUTH MADAYA PROPER",
      "SUGOD PROPER",
      "TAMPILONG",
      "TIMBANGALAN",
      "TOLALI",
      "TONGANTONGAN-TUCA TIMBANGALAN",
      "TOROS",
      "TUCA",
      "TUCA AMBOLONG",
      "TUCA MARINAUT",
      "WAWALAYAN CALOCAN",
      "WAWALAYAN MARINAUT",
    ],
    MAROGONG: [
      "BAGUMBAYAN",
      "BALUT",
      "BITAYAN",
      "BOLAWAN",
      "BONGA",
      "CABASARAN",
      "CADAYONAN",
      "CAHERA",
      "CAIRANTANG",
      "CALUMBOG",
      "CANIBONGAN",
      "DIRAGUN",
      "MANTAILOCO",
      "MAPANTAO",
      "MAROGONG EAST",
      "MAROGONG PROPER (POB.)",
      "MAYAMAN",
      "PABRICA",
      "PAIGOAY CODA",
      "PASAYANAN",
      "PIANGOLOGAN",
      "PURACAN",
      "ROMAGONDONG",
      "SARANG",
    ],
    MASIU: [
      "ABDULLAH BUISAN",
      "ALIP LALABUAN",
      "ALUMPANG PAINO MIMBALAY",
      "BUADI AMLOY",
      "CARAMIAN ALIM RAYA",
      "DALOG BALUT",
      "GINDOLONGAN ALABAT",
      "GONDARANGIN ASA ADIGAO",
      "KALILANGAN",
      "LAILA LUMBAC BACON",
      "LAKADUN",
      "LANCO DIMAPATOY",
      "LOMIGIS SUCOD",
      "LUMBACA INGUD",
      "MACABANGAN IMBALA",
      "MACADAAG TALAGUIAN",
      "MACALUPANG LUMBAC CARAMIAN",
      "MACOMPARA APA MIMBALAY",
      "MAGAYO BAGOAINGUD",
      "MAI DITIMBANG BALINDONG",
      "MAI SINDAOLOAN DANSALAN",
      "MANALOCON TALUB",
      "MARANAT BONTALIS",
      "MATAO ARAZA",
      "MOCAMAD TANGUL",
      "MORIATAO-BAI LABAY",
      "PANTAO",
      "PUTAD MARANDANG BUISAN",
      "SAMBOWANG ATAWA",
      "SAWIR",
      "TALUB LANGI",
      "TAMBORO CORMATAN",
      "TOMAMBILING LUMBACA INGUD",
      "TOWANAO ARANGGA",
      "UNDA DAYAWAN",
    ],
    MULONDO: [
      "BAGOAINGUD",
      "BANGON",
      "BUADI-ABALA",
      "BUADI-BAYAWA",
      "BUADI-INSUBA",
      "BUBONG",
      "BUBONGA GUILOPA",
      "CABASARAN",
      "CAIRATAN",
      "CORMATAN",
      "DALAMA",
      "DANSALAN",
      "DIMARAO",
      "GUILOPA",
      "ILIAN",
      "KITAMBUGUN",
      "LAMA (BAGOAINGUD)",
      "LILOD",
      "LILOD RAYBALAI",
      "LUMBAC (LUMBAC BUBONG)",
      "LUMBACA INGUD",
      "MADAYA",
      "PINDOLONAN",
      "POBLACION (DADO)",
      "SALIPONGAN",
      "SUGAN",
    ],
    "PAGAYAWAN (TATARIKAN)": [
      "AYONG",
      "BANDARA INGUD",
      "BANGON (POB.)",
      "BIALA-AN",
      "DIAMPACA",
      "GUIARONG",
      "ILIAN",
      "KALALUDAN",
      "LININDINGAN",
      "MADANG",
      "MAPANTAO",
      "NGINGIR (KABASARAN)",
      "PADAS",
      "PAIGOAY",
      "PINALANGCA",
      "POBLACION (LUMBAC)",
      "RANGIRAN",
      "RUBOKUN",
    ],
    PIAGAPO: [
      "APOSONG",
      "BAGOAINGUD",
      "BANGCO (POB.)",
      "BANSAYAN",
      "BASAK",
      "BOBO",
      "BUALAN",
      "BUBONG ILIAN",
      "BUBONG TAWA-AN",
      "BUBONGA MAMAANUN",
      "GACAP",
      "ILIAN",
      "ILIAN POBLACION",
      "KALANGANAN",
      "KATUMBACAN",
      "LININDING",
      "LUMBACA MAMAAN",
      "MAMAANUN",
      "MENTRING",
      "OLANGO",
      "PALACAT",
      "PALAO",
      "PALING",
      "PANTAON",
      "PANTAR",
      "PARIDI",
      "PINDOLONAN",
      "RADAPAN",
      "RADAPAN POBLACION",
      "RANTIAN",
      "SAPINGIT",
      "TALAO",
      "TAMBO",
      "TAPOCAN",
      "TAPORUG",
      "TAWAAN",
      "UDALO",
    ],
    "PICONG (SULTAN GUMANDER)": [
      "ANAS",
      "BARA-AS",
      "BIASONG",
      "BULANGOS",
      "DURIAN",
      "ILIAN",
      "LIANGAN (POB.)",
      "MAGANDING",
      "MALADI",
      "MAPANTAO",
      "MICALUBO",
      "MIMBALAWAG",
      "PINDOLONAN",
      "PUNONG",
      "RAMITAN",
      "TOROGAN",
      "TUAL",
      "TUCA",
      "UBANOBAN",
    ],
    "POONA BAYABAO (GATA)": [
      "ATARAGADONG",
      "BANGON",
      "BANSAYAN",
      "BUALAN",
      "BUBONG-DIMUNDA",
      "BUGARAN",
      "CADAYONAN",
      "CALILANGAN DICALA",
      "CALUPAAN",
      "DILAUSAN",
      "DIMAYON",
      "DONGCOAN",
      "GADONGAN",
      "LIANGAN",
      "LUMBAC",
      "LUMBACA INGUD",
      "MADANDING",
      "PANTAO",
      "POBLACION (GATA PROPER)",
      "PUNUD",
      "RAGAYAN",
      "ROGAN CAIRAN",
      "ROGAN TANDIONG DIMAYON",
      "TALAGUIAN",
      "TAPOROG",
    ],
    PUALAS: [
      "BADAK",
      "BANTAYAN",
      "BASAGAD",
      "BOLINSONG",
      "BORING",
      "BUALAN",
      "DANUGAN",
      "DAPAO",
      "DIAMLA",
      "GADONGAN",
      "INGUD",
      "LINUK",
      "LUMBAC",
      "MALIGO",
      "MASAO",
      "NOTONG",
      "PORUG",
      "ROMAGONDONG",
      "TAMBO (POB.)",
      "TAMLANG",
      "TOMAROMPONG",
      "TUKA",
      "YARAN",
    ],
    SAGUIARAN: [
      "ALINUN",
      "BAGOAINGUD",
      "BASAK MAITO",
      "BATANGAN",
      "BUBONG",
      "CADAYON",
      "CADINGILAN",
      "COMONAL",
      "DILAUSAN",
      "DILIMBAYAN",
      "GADONGAN",
      "LIMOGAO",
      "LINAO",
      "LUMBAC TOROS",
      "LUMBAYANAGUE",
      "MALIWANAG",
      "MAPANTAO",
      "MIPAGA",
      "NATANGCOPAN",
      "PAGALAMATAN",
      "PAMACOTAN",
      "PANGGAO",
      "PANTAO RAYA",
      "PANTAON",
      "PATPANGKAT",
      "PAWAK",
      "PINDOLONAN",
      "POBLACION",
      "SALOCAD",
      "SUNGCOD",
    ],
    "SULTAN DUMALONDONG": [
      "BACAYAWAN",
      "BUTA (SUMALINDAO)",
      "DINGANUN GUILOPA (DINGUNUN)",
      "LUMBAC",
      "MALALIS",
      "PAGALONGAN",
      "TAGORANAO",
    ],
    TAGOLOAN: [
      "BAGOAINGUD",
      "BANTALAN",
      "BAYOG",
      "CADAYONAN",
      "DAGONALAN",
      "DIMALAMA",
      "GAYAKAY",
      "INODARAN",
      "KALILANGAN",
      "KIANIBONG",
      "KINGAN",
      "KITAON",
      "MAIMBAGUIANG",
      "MALINAO",
      "MALINGON",
      "MAMA-AN PAGALONGAN",
      "MARAWI",
      "SIGAYAN",
      "TAGOLOAN POBLACION",
    ],
    TAMPARAN: [
      "BALUTMADIAR",
      "BANGON",
      "BERUAR",
      "BOCALAN",
      "CABASARAN",
      "DASOMALONG",
      "DILAUSAN",
      "GINAOPAN",
      "LALABUAN",
      "LILOD TAMPARAN",
      "LILOD TUBOK",
      "LINDONGAN",
      "LINUK",
      "LINUK ORIENTAL",
      "LUMBAC",
      "LUMBACA INGUD",
      "LUMBACA LILOD",
      "LUMBACAINGUD SOUTH",
      "MAIDAN LINUK",
      "MALA-ABANGON",
      "MALIWANAG",
      "MARIATAO DATU",
      "MINANGA",
      "MIONDAS",
      "NEW LUMBACAINGUD",
      "OCCIDENTAL LINUK",
      "PAGALAMATAN LINUK",
      "PAGAYAWAN",
      "PICARABAWAN",
      "PIMBAGO-PAGALONGAN",
      "PINDOLONAN MARIATAO SARIP",
      "POBLACION I",
      "POBLACION II",
      "POBLACION III",
      "POBLACION IV",
      "RAYA BUADI BARAO",
      "RAYA NIONDAS",
      "RAYA TAMPARAN",
      "SALONGABANDING",
      "SAMINUNGGAY",
      "TALUB",
      "TATAYAWAN NORTH",
      "TATAYAWAN SOUTH",
      "TUBOK",
    ],
    TARAKA: [
      "BANDERA BUISAN",
      "BORIONGAN",
      "BOROWA",
      "BUADI AMAO",
      "BUADI AMUNTA",
      "BUADI AMUNUD",
      "BUADI ARORAO",
      "BUADI ATOPA",
      "BUADI DAYOMANGGA",
      "BUADI DINGUN",
      "BUADI ONGCALO",
      "BUCALAN",
      "CADAYONAN BAGUMBAYAN",
      "CARAMAT",
      "CARANDANGAN CALOPAAN",
      "DATU MA-AS",
      "DILABAYAN",
      "DIMAYON",
      "GAPAO BALINDONG",
      "ILIAN",
      "LUMASA",
      "LUMASA PROPER (SALVADOR CONCHA)",
      "LUMBAC BAGOAINGUD",
      "LUMBAC BUBONG MAINDANG",
      "LUMBAC PITAKUS",
      "MALUNGUN",
      "MANGAYAO",
      "MARUHOM",
      "MASOLUN",
      "MORIATAO LOKSA DATU",
      "PAGALAMATAN",
      "PINDOLONAN",
      "PITAKUS",
      "RIRIK",
      "SALIPONGAN",
      "SAMBOLAWAN",
      "SAMPORNA SALAMATOLLAH",
      "SIGAYAN PROPER",
      "SOMIORANG BANDINGUN",
      "SUNDING",
      "SUNGGOD",
      "SUPANGAN",
      "TUPA-AN BUADIATUPA",
    ],
    TUBARAN: [
      "ALOG",
      "BAGIANGUN",
      "BETA",
      "CAMPO",
      "DATUMANONG",
      "DINAIGAN",
      "GADONGAN",
      "GAPUT",
      "GUIARONG",
      "MADAYA",
      "MALAGANDING",
      "METADICOP",
      "MINDAMUDAG",
      "PAGALAMATAN",
      "PAIGOAY-PIMBATAAN",
      "POBLACION (BURIBID)",
      "POLO",
      "RIANTARAN",
      "TANGCAL",
      "TUBARAN PROPER",
      "WAGO",
    ],
    TUGAYA: [
      "BAGOAINGUD",
      "BUADI ALAWANG",
      "BUADI DICO",
      "BUBONG",
      "CAMPONG TALAO",
      "CAYAGAN",
      "DANDANUN",
      "DILIMBAYAN",
      "GURAIN",
      "LUMBAC",
      "MAIDAN",
      "MAPANTAO",
      "PAGALAMATAN",
      "PANDIARANAO",
      "PINDOLONAN I",
      "PINDOLONAN II",
      "POBLACION (INGUD)",
      "PUTAD",
      "RAYA",
      "SUGOD I",
      "SUGOD MAWATAN",
      "SUMBAGA ROGONG",
      "TANGCAL",
    ],
    WAO: [
      "AMOYONG",
      "BALATIN",
      "BANGA",
      "BO-OT",
      "BUNTONGUN",
      "CEBUANO GROUP",
      "CHRISTIAN VILLAGE",
      "EASTERN WAO",
      "EXTENSION POBLACION",
      "GATA",
      "KABATANGAN",
      "KADINGILAN",
      "KATUTUNGAN (POB.)",
      "KILIKILI EAST",
      "KILIKILI WEST",
      "MALAIGANG",
      "MANILA GROUP",
      "MILAYA",
      "MIMBUAYA",
      "MUSLIM VILLAGE",
      "PAGALONGAN",
      "PANANG",
      "PARK AREA (POB.)",
      "PILINTANGAN",
      "SERRAN VILLAGE",
      "WESTERN WAO (POB.)",
    ],
  };
}
